### PR TITLE
WIP: Scaling

### PR DESCRIPTION
**Pull request by WTRipper**
This is a WIP aproach for scaling. I am still testing and experimenting but feedback is apreciated. Current status: 
- Desktop has a ScaleX and ScaleY property
- (Min/Max)Width, (Min/Max)Width, Left and Top are scaled on getting their values
- Methods are in place to allow to set above properties to ignore scaling

If this way works out it probably would make sense to implement it as well for padding and margins.

### CODE REVIEW

**Comment by WTRipper** [comment]
To make it work one would have go through every use of the (Min/Max)Width, (Min/Max)Width, Left and Top setters and check whether the value has to be scaled because otherwise the scaling factor will be applied multiple times. E.g. think of horizontally aligning an element to the center of it's parent: element.Left depends on the scaled Width of it's parent and is scaled by it's own.
I am not 100% sure if this would be the right way to do it. Maybe it makes more sense to have additional properties: Scaled* (e.g. ScaledMinWidth) that are read only for rendering and input interpretation.

**Comment by WTRipper** [comment]
On the other hand having only those Scaled* Properties and applying scaling there will not suffice either. You would still need to differentiate between values that were insert as pixel values by the dev and relative values calculated by ExpressionParser, Alignments or Proportions.

**Comment by rds1983** [comment]
I dont like idea of public properties returning their scaled value instead of value the user had set.
Probably it's better to add additional protected properties that used only for layout/rendering.

**Comment by rds1983** [comment]
Now Myra widgets & Desktop support transformations: https://github.com/rds1983/Myra/wiki/Widget-Transformations
Hence closing the PR.

**Pull request closed without merging**
