### PR TITLE
Update to FontStashSharp 0.9.4

### PR DESCRIPTION
**Pull request by realvictorprm**

### CODE REVIEW

**Comment by realvictorprm** [comment]
I'm aware, that C# 8 is not completely supported by the .NET Framework, however what I'm using is within what is supported because it's just syntactical changes, see [this](https://stackoverflow.com/questions/56651472/does-c-sharp-8-support-the-net-framework) SO post.

**Comment by realvictorprm** [comment]
Side note, from the list what is not compatible, I don't think this library will run into this.

**Comment by rds1983** [comment]
Thanks, @realvictorprm.

**Comment by realvictorprm** [comment]
Happy to help @rds1983 :)

**Pull request merged**
