### PR TITLE
Remade colour picker UI

### PR DESCRIPTION
**Pull request by Felix-Schmid**
To make the colour picker more intuitive, I remade the UI to be more similar to other programs. Although I am not too happy about my implementation (for example: I tried to make the colour wheel with a shader, but couldn’t really find a way to do it, so now it’s just an image), I think it works quiet well. Anyway, here is how my version looks like:

Colorpicker_new

Also, while working on the colour picker, I noticed that there is a problem with transparency in the Monogame version, where it only works as intended with the colour Black and doesn’t work at all with White. This is because in the RenderContext class, the BlendState is set to AlphaBlend, where Monogame expects pre-multiplied colours. Setting it to NonPremultiplied fixes the transparency issue, but somehow messes up text rendering, so I was not able to fix it.

### CODE REVIEW

**Comment by rds1983** [comment]
Well, original ColorPickerDialog was made just "to make monkey dance". I lack any designer skills, so it looked awful.
Tyvm!

**Comment by rds1983** [comment]
As for the problem, I've created corresponding issue - #213 
Hopefully it'll get fixed.

**Comment by Nornec** [comment]
Something else that I may suggest, which I've written a custom version of in my code, is to abstract the color picker into a panel instead of a dialog (re: ColorPickerPanel) which can then be implemented in a pane, dialog, or even a tooltip. This essentially externalizes the functionality to be used anywhere a panel can.

**Comment by rds1983** [comment]
great idea, @Nornec.
I've created corresponding issue - #214

**Pull request merged**
